name: alfred_so
description: Search for answers on StackOverflow from Alfred

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.4

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  args: ^2.4.1
  alfred_workflow: ^0.3.3
  autoequal: ^0.5.1
  cli_script: ^0.3.1
  crypto: ^3.0.3
  collection: ^1.17.2
  envied: ^0.3.0+3
  equatable: ^2.0.5
  html_unescape: ^2.0.0
  http: '>=0.13.6 <2.0.0'
  json_annotation: ^4.8.1
  path: ^1.8.3
  stash: ^4.5.3

dev_dependencies:
  autoequal_gen: ^0.5.1
  build_runner: ^2.4.4
  dart_code_metrics: ^5.7.4
  envied_generator: ^0.3.0+3
  json_serializable: ^6.7.0
  lints: ^2.1.0
